services:
  projectdb:
    image: mysql:8.0.34
    container_name: projectdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: operis_project
      MYSQL_USER: operis
      MYSQL_PASSWORD: root
    ports:
      - "4444:3306"
    volumes:
      - projectdb_data:/var/lib/mysql
volumes:
  projectdb_data:
